### ISSUE TITLE
Parts of mesh not exporting weight properly

### ISSUE THREAD

**Issue by stormygaret15** [RazTools/Studio#10]
When i export some mesh is missing its weight information. Can you please take a look? Thank you. 
![Blender 13_8_2023 9_01_21 pm](https://github.com/RazTools/Studio/assets/83821164/b9f64858-663e-42aa-960c-6d26d5f42ac0)
[help.zip](https://github.com/RazTools/Studio/files/12329567/help.zip)

**Comment by Razmoth** [comment]
Greetings,

Will try to check

**Comment by Razmoth** [comment]
Greetings,

Should be fixed in the latest release.
![image](https://github.com/RazTools/Studio/assets/32140579/3e85dfdb-2be2-4c1f-b81a-4786462a7f5c)
