### ISSUE TITLE
Nothing exported

### ISSUE THREAD

**Issue by 28598519a** [RazTools/Studio#13]
Hi,

PathID 7 Texture2D nothing exported.
PathID 8-12 Shader System.OverflowException

When ID7 loading, it didn't have any error, but failed to export.
And ID8-12 not loadable, but shader is unimportant.

Bundle Version: 2022.2.1f1
Sample:
[BeginningSpine.zip](https://github.com/RazTools/Studio/files/12528234/BeginningSpine.zip)

thanks.

**Comment by Razmoth** [comment]
Greetings

The game has customized types,

![image](https://github.com/RazTools/Studio/assets/32140579/2a2c10ba-cf1c-4e17-afbe-bfb2dcbf02ed)

To load `Texture2D`, add this line in `Texture2D.cs`:

![image](https://github.com/RazTools/Studio/assets/32140579/e0329257-a2a0-4c2b-a932-9437d625c935)

**Comment by 28598519a** [comment]
It doesn't seems to be a customized types issue, but rather that version 2022.2 is not supported in version 1.0.0.0

Noted this commit:
https://github.com/RazTools/Studio/commit/df186e891bdc896a7d89779af9d76cbc64c094c9

Also read and export successfully with the latest build version.
