### ISSUE TITLE
Animation export issue (v0.90.00) and file read-in error (v0.90.10)

### ISSUE THREAD

**Issue by UnicornSaiKou** [RazTools/Studio#14]
Weapon animations using PGR extracted with v0.90.00 will have individual bones strangely misaligned（Bone16&bone17，These two bones are supposed to be parallel and symmetrical, but bone17 is strangely misaligned as shown in the picture）
![P6STOA7DZW4WIS2](https://github.com/RazTools/Studio/assets/58694632/086ea406-aee3-4d9e-a044-234ac5fd314c)

and attempting to extract the PGR file with v0.90.10 will display the following error message
![R3MZ817GLBMSD20_37](https://github.com/RazTools/Studio/assets/58694632/6e0600b2-4e4c-4c2e-8b52-2e5173ff8d95)

These are the source files, I exported Animator "E3SwordMd130111P01" and AnimationClip "Change04".
[files.zip](https://github.com/RazTools/Studio/files/12552587/files.zip)

**Comment by Razmoth** [comment]
Greetings,

The `v0.90.10` issue should be fixed now in the latest build action artifacts [here](https://github.com/RazTools/Studio/actions/runs/6209770897)

As for the bones issue in `v0.90.00`, will need to investigate more.

**Comment by Razmoth** [comment]
Greetings,

Should be fixed in the latest release.
![image](https://github.com/RazTools/Studio/assets/32140579/a35f8b77-8b66-4390-a65c-08e5c2a04352)
