### ISSUE TITLE
Fix not supporting CN unity games

### ISSUE THREAD

**Issue by EoberdLee** [RazTools/Studio#16]
Fix not supporting CN unity games：naruto mobile unity ver：2021.03.16f which cant export by any method

**Comment by Modder4869** [comment]
if it is unitycn game then you have to find the key yourself , also at least send package name or link to it or file sample

**Comment by EoberdLee** [comment]
I'm sorry for my stupidity, I don't really understand the mechanism design of this platform, I'm a newbie, sorry, this is the og package of apk file, you all have made an amazing project, I really admire it You guys, if there’s anything I don’t do well, I’ll learn from it. I love you.
https://mega.nz/folder/cmEQzLJA#M4b1HVy-5uHFZzKMdwtCVA

**Comment by tetsuki02** [comment]
> if it is unitycn game then you have to find the key yourself , also at least send package name or link to it or file sample

how to find the key sir ??
maybe i have some issue, cuz i dont know how to search key

**Comment by Modder4869** [comment]
> > if it is unitycn game then you have to find the key yourself , also at least send package name or link to it or file sample
> 
> how to find the key sir ?? maybe i have some issue, cuz i dont know how to search key

need some basic knowledge about reverse engineering "games"

**Comment by Razmoth** [comment]
Greetings,

The game's provided assets does not resemble that of `UnityCN`, it has another type of encryption.
