### ISSUE TITLE
About Phasmo - Studio not loading entire phasmo folder

### ISSUE THREAD

**Issue by Neinndall** [RazTools/Studio#19]
Hello!
I saw the previous thread #11 that you closed and I couldn't follow the conversation, however, I wasn't 100% sure if you could see it when writing a comment, however, I'm opening another thread to clarify everything.

I was testing the new version and I tell you.

`File/Load Folder` and `Phasmophobia`

After that...
![image](https://github.com/RazTools/Studio/assets/66384195/19372c11-f040-42eb-8322-3acd7129d3b8)

So, Studio forces me to upload individual files... appear again the microsoft net error
Is there no solution for this?

You said to use an external tool to unzip and then use Studio, but my question is, is it not possible to upload the entire folder? I will have to upload file by file `including the heavy file that give error when upload folder`, **because if I upload file by file, studio loads them without errors.**

Thx! ^^

**Comment by Razmoth** [comment]
Greetings, 

This issue happens because the stream size is larger than maximum size of array supported by `.NET`, hence why this error keeps on showing.

I'd suggest to extract it in a separate folder and try to load from that.
