### ISSUE TITLE
Support Final Fantasy Ever Crisis?

### ISSUE THREAD

**Issue by ngovandang** [RazTools/Studio#21]
https://forum.xentax.com/viewtopic.php?p=194637

> Found Criware Decrypt key, but I'm not too sure if it's the same key used everywhere.
> Key: 19629307353822
> Key(Hex): 0x000011da4de45ade
> Files seem to be contained in AFS2 and ACB/AWB files as I've seen.

Is this possible?

**Comment by Modder4869** [comment]
this issue is not related to this tool
