### ISSUE TITLE
some textures look garbled and/or do not decode correctly (Baten Kaitos I&II HD Remaster Digital Artbook)

### ISSUE THREAD

**Issue by modusc896d352** [RazTools/Studio#22]
so, i decided to test RazTools' Studio with a couple of files from a nintendo switch game (**Baten Kaitos I&II HD Remaster**) and with it came a "digital artbook" of sorts that showcases a lot of the art from the game. as it turns out, a lot of assets with "Sprite" and "Texture2D" as their type would turn out garbled and/or downright incomprehensible to look at.

here are four "Sprite" assets, in no particular order.
[https://files.catbox.moe/go46of.png](https://files.catbox.moe/go46of.png)
[https://files.catbox.moe/g23q6y.png](https://files.catbox.moe/g23q6y.png)
[https://files.catbox.moe/ttzmln.png](https://files.catbox.moe/ttzmln.png)
[https://files.catbox.moe/uqw69a.png](https://files.catbox.moe/uqw69a.png)

and here are eight "Texture2D" assets.
[https://files.catbox.moe/fhuhfz.png](https://files.catbox.moe/fhuhfz.png)
[https://files.catbox.moe/6lf7tc.png](https://files.catbox.moe/6lf7tc.png)
[https://files.catbox.moe/p4fbs2.png](https://files.catbox.moe/p4fbs2.png)
[https://files.catbox.moe/ttuk9m.png](https://files.catbox.moe/ttuk9m.png)
[https://files.catbox.moe/scqw0y.png](https://files.catbox.moe/scqw0y.png)
[https://files.catbox.moe/6d3mod.png](https://files.catbox.moe/6d3mod.png)
[https://files.catbox.moe/mu9lo9.png](https://files.catbox.moe/mu9lo9.png)
[https://files.catbox.moe/1ozy0h.png](https://files.catbox.moe/1ozy0h.png)

i can upload the raw files themselves if needed.

**Comment by Razmoth** [comment]
Greetings,

These textures seems to be swizzled, try to use nes's version instead:
https://github.com/nesrak1/AssetStudio/tree/switch-tex-deswizzle

**Comment by modusc896d352** [comment]
artifact link for nesrak1's version seems to have expired. i don't have much time to compile them myself.

**Comment by modusc896d352** [comment]
so, i was at a stage where i could finally compile nes's version by myself (using VS2022 plus some required .NET components, of course) so i can finally used it
but by the time i got to this point i got 6 errors about "fbxsdk.h" not existing which made VS2022 just stop compiling the whole thing altogether.

oh well. it was fun while it lasted.
