### ISSUE TITLE
Jump Assemble - Need Help Decrypt/Extract .AB File

### ISSUE THREAD

**Issue by YukihimeX** [RazTools/Studio#23]
**Game:** Jump Assemble (Codename Jump)
**Game Samples: 80.0MB** (A few random AB Files) [https://mega.nz/file/NDA2CC6T#Vrwb8q3oZ ... CGR5TLm4Os](https://mega.nz/file/NDA2CC6T#Vrwb8q3oZTuuMKP_CtA1o-hLr7-WOSjtHCGR5TLm4Os)
**APK Download Links:**
[https://apkcombo.com/codename-jump/com. ... 3.android/](https://apkcombo.com/codename-jump/com.dgames.g15002003.android/)
https://modcombo.io/jump-assemble.html
https://apkrabi.com/jump-assemble/

Hi, so the new MOBA game Jump Assemble (AKA Codename Jump) look really nice but all the assets is in .AB file format. I tried AssetBundleExtractor but ended in failure.
Just wondering if anyone could help extract it, so it would load on AssetStudio.

**Game Screenshots**
![hq720](https://github.com/RazTools/Studio/assets/50353278/040d20c3-dca8-441f-b7fa-73ad4442d88c)
![maxresdefault (1)](https://github.com/RazTools/Studio/assets/50353278/19869032-9e28-4c42-ab6d-2416778bfaf0)

**Comment by Razmoth** [comment]
Greetings,

Added under `CodenameJump`.

**Comment by atsniperthin** [comment]
It seems that .ab files doesn't have a UnityFS header and AssetStudio won't load.

I'm not sure if I have done anything wrong.
![image](https://github.com/RazTools/Studio/assets/46410060/c02cf5de-86a4-4235-8d1f-32d3bc714afc)

**Comment by imbachoii** [comment]
Hello, can we have an updated verion of AssetStudio in this game? seems like it won't work now. Thank you.
