### ISSUE TITLE
Codename Jump .AB doesn't have UnityFS header

### ISSUE THREAD

**Issue by atsniperthin** [RazTools/Studio#24]
the asset was from SEA CBT

https://drive.google.com/file/d/1bLfAUttjIuSGo29gM_QcC1lk2KnS8cwP/view?usp=sharing

![image](https://github.com/RazTools/Studio/assets/46410060/dc9b108f-7ac5-4e75-bbec-77377d32863f)

**Comment by atsniperthin** [comment]
it seems that in CBT they changed encryption so i hope you could do something about it

**Comment by Razmoth** [comment]
Greetings,

It is possible to dump the key from `global-metadata.dat` and replace it with the existing one to support that version.
