### ISSUE TITLE
SUGGESTION: Call of Duty Mobile

### ISSUE THREAD

**Issue by kuletxcore** [RazTools/Studio#25]
All assets of Call of Duty: Mobile are currently encrypted, and all attempts of extraction using the original AssetStudio have failed, as no one knows how to decrypt it.

It would be very appreciated if you guys somehow figure out how to extract assets like weapons, operator skins, hand models, and more.

There are multiple versions of this game. The Chinese and Garena versions have more content than the Global version of CODM, and some exclusives can only be found on those versions.

Thank you so much, and I hope you consider this as a new addition to Studio!

**Comment by Razmoth** [comment]
Greetings,

The game seems to be using a custom packaging file system, rather than the standard `UnityFS`.

Most likely it will not be supported due to that reason.

**Comment by kuletxcore** [comment]
Oh, that's why... Thanks for replying!
