### ISSUE TITLE
Does this support PGR PC?

### ISSUE THREAD

**Issue by RedoCode** [RazTools/Studio#26]
Or is it only the mobile version supported?

**Comment by Modder4869** [comment]
try instead and yes it should support both

**Comment by RedoCode** [comment]
Was not able to extract/load anything related to the game using pc version (model, animation etc.)

**Comment by Modder4869** [comment]
which key you picked? follow [this](https://gist.github.com/Modder4869/0f5371f8879607eb95b8e63badca227e#unitycn) if you dont know how

**Comment by RedoCode** [comment]
I see what I did wrong, tyvm!
