### ISSUE TITLE
Not working in Honkai Impact CN7.0

### ISSUE THREAD

**Issue by KotoriKoi** [RazTools/Studio#27]
![92 F8@Y0LT7QPR)ZWS2PW@8](https://github.com/RazTools/Studio/assets/91445888/0c9c9a52-c964-4473-bcd0-66d1c2d604f7)

Is this a personal reason on my part or is it unsupported?

**Comment by Modder4869** [comment]
what studio version you using make sure it is [this](https://nightly.link/RazTools/Studio/workflows/build/main) and upload file sample if that still didnt work
