### ISSUE TITLE
SUGGESTION: Overlord mass dessert and FGO. Also problem with RAM

### ISSUE THREAD

**Issue by axeleratorVector** [RazTools/Studio#28]
Overlord on Unity, and I even accidentally managed to connect two codes to decrypt files, but alas, this file was lost. (I'm not a programmer, I just connected two existing codes and they worked) In any case, it is possible to decrypt the files.
As for the FGO, I’m no longer sure how it works, but I good be possible open it.
same i write problem message. Quite often, when opening game files of 1-4 GB (all files game), RAM takes up more than 30 GB, and it happens that this is not even half the progress of opening files.And its do broke programm and can do bad thing with PC. Ultimately, AssetStudio.GUI often becomes useless for opening the this files, because died, after after RAM is full. (AssetStudio.CLI does not have such problems, but it cannot normally export textures and models at the same time as in AssetStudio.GUI, and generally has more limited functionality.)

**Comment by Razmoth** [comment]
Greetings,

This issue usually happens when games have customized type tree definitions, which according to your description seems to be the case, try disabling `Renderer/Shader/AnimationClip` from `Export Options` and load again and see if that helps.

**Comment by axeleratorVector** [comment]
after disabling Renderer/Shader/AnimationClip, it started to take up 98% of the RAM, (32GB of RAM in total), but still allowed me to download all the files, thanks.
