### ISSUE TITLE
Why skip legacy animation clip

### ISSUE THREAD

**Issue by AkiKurisu** [RazTools/Studio#29]
I saw a validation added in AnimationClipExtension on [Commit](https://github.com/RazTools/Studio/commit/27a7de1fe0493cff6bf1584c0da91eee7fad7632). Why we skip legacy animation clip now ?

**Comment by Modder4869** [comment]
thats only for preview , legacy/generic can be export merged with model itself , `Export Animator+Selected AnimationClips`
