### ISSUE TITLE
extract mecharashi assets error

### ISSUE THREAD

**Issue by PackageInstaller** [RazTools/Studio#30]
![image](https://github.com/RazTools/Studio/assets/80018096/75038f7f-2dce-4d8c-aa56-3a724f45a4ca)

As shown in the picture, there was an error in extracting the assets, maybe they changed the UnityCN key?

sample：https://drive.google.com/file/d/1lwIZG5LwnsslqEB7jpZNg9DZpYUOtYHl/view?usp=share_link

Official website: https://ma.zlongame.com/ （It starts testing pre-downloads today）

**Comment by Modder4869** [comment]
your link didnt include metadata , and what make you think it is unitycn? and if so what key you picking

**Comment by PackageInstaller** [comment]
Because it is recorded in the keys.json file of the UnityCN key
![image](https://github.com/RazTools/Studio/assets/80018096/b76c7eb9-eee2-4058-bfc7-79ae947d069b)
this metadata file link : https://drive.google.com/file/d/19GEs3Svzh6_R93AsR7h3jAjXzUbEiVNT/view?usp=share_link

I'm not very good at programming stuff so I'm trying to ask for help🙏🏻

**Comment by PackageInstaller** [comment]
This is the command I executed in the terminal

`AssetStudioCLI.exe "Z:\Rikka\Downloads\Unpack Games\钢岚_2.4.0\ExportAssetBundle" "Z:\Rikka\Downloads\Unpack Games\钢岚_2.4.0\output" --game UniyuCN --key_index 7`

**Comment by Modder4869** [comment]
should be 31433743463543423144313841304630 , you can close the issue if it works for you

**Comment by PackageInstaller** [comment]
> should be 31433743463543423144313841304630 , you can close the issue if it works for you

It's working fine, thank you very much for your help🥰
