### ISSUE TITLE
SUGGESTION - Export audio as .OGG

### ISSUE THREAD

**Issue by Neinndall** [RazTools/Studio#31]
I only see the possibility in export options to export the audio as .wav but not as ogg.

**Comment by Razmoth** [comment]
Greetings,

Current the audio type is exported based on the original type of the data stored in `AudioClip`, conversion should be done outside of `AssetStudio` scope.
![image](https://github.com/RazTools/Studio/assets/32140579/09251406-4cdd-4447-b264-16e60acdde7e)
