### ISSUE TITLE
你好，我在导出GI中的部分文件时遇到了问题。

### ISSUE THREAD

**Issue by liTongQ** [RazTools/Studio#35]
我想导出GI游戏中的 spine 文件，它由图片，skel 和 atlas 文件构成， atlas 文件可以使用记事本直接打开。
在导出的时候图片和 skel 文件都可以正常导出，只有atlas文件只能以 Raw 方式导出，并且导出后的文件前后都出现了乱码字符。我不知道哪里有问题。
如果选中文件后 Export >Selected assets，会出现：[Info] Error while read type, read 76 bytes but expected 8004 bytes
如果选中文件后 Export >Raw>Selected assets，会导出 .dat 文件，使用记事本打开后，会发现文件前后都出现了乱码字符，而中间的内容是正常的。
并且 AssetStudioCLI 不能设置以 Raw 方式导出。
另外，AssetStudioCLI  可以增加在 --types 上使用正则表达式的功能吗？

**Comment by Modder4869** [comment]
there is no need for regex on types filter , as for MonoBehaviour i think thats normal you can just write some script to remove the unwanted bytes from header

**Comment by liTongQ** [comment]
谢谢你的回复。
另外 AssetStudioCLI 不能设置以 Raw 方式导出。这意味着我必须使用 AssetStudioGUI.exe 打开所有文件，选择好之后使用 Raw 方式导出。有没有什么更方便快捷的方法导出呢？

**Comment by Razmoth** [comment]
Greetings,

It should be added now under `--export_type` option.

**Comment by liTongQ** [comment]
感谢你的回复与修改！
但很抱歉我没有能力将源码打包成可以使用的exe文件，我只能等待下一次更新安装包 (╥﹏╥)。
非常期待你的下一次更新 (*'▽'*)

**Comment by Modder4869** [comment]
can download from [here](https://nightly.link/RazTools/Studio/workflows/build/main)

**Comment by liTongQ** [comment]
你真的太棒了！！！我立刻下载了新的文件！
在新的文件里，我使用了  `AssetStudio.CLI.exe G:\GI\01019299.blk G:\GI2 --game=GI --types=MonoBehaviour --names="Gcg_CardFace_Char.*." --group_assets=None --export_type=Raw`
但没有成功输出内容，什么都没有发生。我不确定是不是我理解错了。
![image](https://github.com/RazTools/Studio/assets/78954543/545e6fb9-75a3-410c-a350-33c2f062f113)

**Comment by Modder4869** [comment]
try just --types MonoBehaviour

**Comment by liTongQ** [comment]
我尝试结束了，还是没有任何输出，或许我可以将这个文件发送给你。
[01019299.zip](https://github.com/RazTools/Studio/files/13400767/01019299.zip)

**Comment by Modder4869** [comment]
you need to add --dummy_dlls '.' or any path it seems to ignore MonoBehaviour if dummy_dlls not set

**Comment by liTongQ** [comment]
很抱歉，我不能理解 dummy_dlls ，我不知道应该放什么路径上去。我对这个几乎没有了解 (╥﹏╥)。

**Comment by Modder4869** [comment]
> Sorry, I can't understand dummy_dlls, I don't know what path I should put it in. I know almost nothing about this (╥﹏╥).

any path just do `--dummy_dlls '.'` it doesnt matter what you put there 
so full should be something like `.\AssetStudio.CLI.exe "01019299.blk" "output" --game GI --types MonoBehaviour --export_type Raw --dummy_dlls '.'
`

**Comment by liTongQ** [comment]
谢谢你，你太厉害了！我使用了这个之后，还是发生了错误，但是我尝试改为 `--dummy_dlls "." `之后成功运行了！

我的问题已经解决了，接下来我可以使用其他脚本删除这个文件开始和结束处的乱码字符了！！(^▽^) 

![image](https://github.com/RazTools/Studio/assets/78954543/78d5a9ac-67cf-4f42-8e3a-61d88f52de54)
