### ISSUE TITLE
Exported character animation has foot sliding error

### ISSUE THREAD

**Issue by ShiinaRinne** [RazTools/Studio#38]
This error occurs when I export animations from *Project Sekai*
You can reproduce this error by playing it directly in Unity.
I have tried enabling animation IK and disabling animation compression, but neither solved the issue

And it also appears in Maya and Blender, not just in Unity, so I guess it might be an error during the conversion?
btw, I also tried making a new animation, packaging it as an asset bundle, and then extracting it, but I did not observe the same problem.

https://github.com/RazTools/Studio/assets/45081750/fd837416-c866-4bbd-8be2-283f59de3e77

Exported fbx file:
https://drive.google.com/file/d/1i4FxdR2QZbNKjTmiZy1MRuMfjInHuutZ/view?usp=drive_link
Original asset bundle:
https://drive.google.com/file/d/1A53mERhhVt3jeKRHiCUzM5NFZ-g_xvfx/view?usp=sharing

**Comment by Kimoyo-Kun** [comment]
Hi, the animations are alright, characters are applied a special scale in game depending on their height.

**Comment by ShiinaRinne** [comment]
Thanks for your reply~ 
Is it working properly in your Unity?
In my test, the characters and animations used are matched in the game (Miku is action 6) but still have this issue
[2023-11-27 13-55-38.zip](https://github.com/RazTools/Studio/files/13470237/2023-11-27.13-55-38.zip)
![image](https://github.com/RazTools/Studio/assets/45081750/b695199a-8110-4104-bbe4-16d4fdf05471)
![image](https://github.com/RazTools/Studio/assets/45081750/45aa8dc3-190a-4b2b-b94e-3326924be7a0)



fbx and anim:
[body.zip](https://github.com/RazTools/Studio/files/13470255/body.zip)
