### ISSUE TITLE
Could you please add the support for the new game zzz_cb2?

### ISSUE THREAD

**Issue by Dongyifengs** [RazTools/Studio#39]
Can you add an unpack of zzzcb2? I really need it

**Comment by Modder4869** [comment]
https://mega.nz/folder/o1oHyIIb#kd3EZO2xAgIvPMBCFkB7aQ/folder/M44EHK7K

**Comment by Dongyifengs** [comment]
> https://mega.nz/folder/o1oHyIIb#kd3EZO2xAgIvPMBCFkB7aQ/folder/M44EHK7K 

Could you give me the source code?
thank you

**Comment by Modder4869** [comment]
there wont be any as game is not public yet , can use dnSpy or similar to decompile dll

**Comment by Dongyifengs** [comment]
> there wont be any as game is not public yet , can use dnSpy or similar to decompile dll 

OK thank you.
