### ISSUE TITLE
Issue with this game

### ISSUE THREAD

**Issue by ngovandang** [RazTools/Studio#4]
Can you check why are assets from this game causing error on load?

https://mega.nz/file/Xhh3DCSI#tmWvgUDjKTXZI6OMlVR_e6mjpJr6ju62Ni54leQbeTg

**Comment by Razmoth** [comment]
Greetings, 

Check `Options -> Export Options -> Disable Shader` and try again.

**Comment by ngovandang** [comment]
worked, thank you
