### ISSUE TITLE
Battle Teams 2 support?

### ISSUE THREAD

**Issue by rojok23** [RazTools/Studio#40]
Hello, I was wondering if you could have a look at some of these samples for the game Battle Teams 2.
https://mega.nz/file/N6oBWI6Z#aFuEOW92db_fHH2ViKzVtL1HScua77vTZtYyfTb-f8w
The files were found in an assetbundleres folder and if you need any additional files I can see about uploading them. Thank you for your time.

**Comment by Razmoth** [comment]
Greetings,

The provided sample files has encrypted blocks, this is not considered an issue.

**Comment by Razmoth** [comment]
Greetings,

seems like the blocks xor key is `0B1DA7FB078524A5457872DB26582B92`.

**Comment by rojok23** [comment]
Sorry for replying to closed, but I have to ask; Using the key above do I put it into the UnityCN Key field?
