### ISSUE TITLE
Honkai Impact 3rd Meshes do not export

### ISSUE THREAD

**Issue by AverageTrapEnthusiast** [RazTools/Studio#44]
Meshes from honkai impact 3rd do not seem to export with geometry when exporting from current game versions.

**Comment by Modder4869** [comment]
what does this even mean

**Comment by AverageTrapEnthusiast** [comment]
read the guide in readme, animators do not export with any mesh data in current version of tools. Only exports with empties in place of bones and such.
![image](https://github.com/RazTools/Studio/assets/49507276/f59b9f65-eee3-44de-90cb-8457cc85ab3b)

**Comment by AverageTrapEnthusiast** [comment]
^ new griseo battlesuit attempted export

**Comment by Modder4869** [comment]
reply on discord , and download latest actions not release and make sure after you build cabmap you are selecting it and you need betterfbx to import
