### ISSUE TITLE
It seems Neural Cloud's UnityCN key was changed

### ISSUE THREAD

**Issue by newbiestat** [RazTools/Studio#46]
Neural Cloud CN has updated today to version number "2.0.3".

After that, it seems the UnityCN key was also changed.

The existing UnityCN key for Neural Cloud, "31636162383436663532393031633965" does not working anymore.

Are there any methods to get the changed UnityCN key?

Or would you see this game and find the UnityCN key?

**Comment by Razmoth** [comment]
Greetings,

Added.

**Comment by newbiestat** [comment]
> Greetings,
> 
> Added.

I didn't expect you to reply so quickly.

Confirmed the changed UnicyCN key is working well.

Your work has helped me in many ways, thank you so much.
