### ISSUE TITLE
muv luv dimensions support

### ISSUE THREAD

**Issue by DDXDB** [RazTools/Studio#48]
This game has been bothering me for a long time
It seems that il2cpp is enabled, and a large number of resources are obtained via hot update.
google play:https://play.google.com/store/apps/details?id=jp.co.nextninja.dimensions&hl=ja&gl=jp
hot update pack:(As of Nov 19, 2023) https://1drv.ms/u/s!Akiq9eKkT_m3mUhhbs_MOntSM5Dg

**Comment by Modder4869** [comment]
please ask in unitypy or reshax discord , github issues are meant to be studio issues not for requests
