### ISSUE TITLE
issue with this game

### ISSUE THREAD

**Issue by zhuangge525** [RazTools/Studio#5]
[story_prefab_211.zip](https://github.com/RazTools/Studio/files/12060285/story_prefab_211.zip)
Could not parse the game, Can you see the problem? thank you!

**Comment by Razmoth** [comment]
Load the game with `AlchemyStars` profile and set the unity version manually in `Options -> Specify Unity Version` as the version is stripped from bundle.

**Comment by zhuangge525** [comment]
worked, thank you
