### ISSUE TITLE
Not working some Imaginary Fest files

### ISSUE THREAD

**Issue by donsoy** [RazTools/Studio#51]
I tried following the tutorial, but only part of it worked.
Is there a different way to do it?
It seems some files have different key length.

**Comment by Modder4869** [comment]
what tutorial? for imaginary fest you need to select it as game and have file structured same way as how game download them

**Comment by donsoy** [comment]
this tutorial "https://gist.github.com/Modder4869/0f5371f8879607eb95b8e63badca227e"
all files were placed as they are.
then, I selected specify game IF, and built map.
only one-third of them were opened,but the rest are removed.
is  it possible to open these encrypted files, or did I make a mistake?

**Comment by Modder4869** [comment]
if removed then it is not asset or decryption failed send one sample along full path of failed file

**Comment by donsoy** [comment]
"https://drive.google.com/file/d/10VkKx0DtZ01URS8Ts9jH03dLxNzeOzqS/view?usp=sharing"

**Comment by Modder4869** [comment]
still need full path to it not just file itself

**Comment by donsoy** [comment]
![path](https://github.com/RazTools/Studio/assets/149079261/3ed839f6-5c11-4a87-8589-868f934de294)

**Comment by donsoy** [comment]
"D:\data\data\com.square_enix.android_googleplay.index_if\files\data\e73e7859029d5c10f5036b44fec2c4a102411bb0029d955ebacfa5c7"

i'm sorry

**Comment by Modder4869** [comment]
path should be something like 7b/7aca6026a1fd767d0cc74badfc0758c2a9a28b60a1fd76d47911e4bb at least thats what bundle one was

**Comment by donsoy** [comment]
I tried the same path but got same error issues #49.
it remained removed.

**Comment by Modder4869** [comment]
you arent supposed to use same path as what i sent it was example the parent folder `7b` where file is is important for decryption if game is not downloading it like that then maybe file not supported or you doing something wrong when copying

**Comment by donsoy** [comment]
thank you so much.
I'll check all of them again.
