### ISSUE TITLE
Error when parsing AnimationClips

### ISSUE THREAD

**Issue by redsigma** [RazTools/Studio#52]
I am getting this error when parsing some AnimationClips for GI 4.3
`System.IO.EndOfStreamException: Unable to read beyond the end of the stream`

![image](https://github.com/RazTools/Studio/assets/20425476/241633e0-4de4-448d-a0c8-ffcad9a6e7b4)

Another error that rarely happens:
`System.OverflowException: Arithmetic operation resulted in an overflow`

![image](https://github.com/RazTools/Studio/assets/20425476/d8e30fbe-d20b-4c0e-9b8a-8f424d529a08)

**Comment by Razmoth** [comment]
Greetings,

This issue has been fixed, make sure to use the latest build action available [here](https://nightly.link/RazTools/Studio/workflows/build/main).
