### ISSUE TITLE
[request] have AssetMap include MonoBehaviour entries

### ISSUE THREAD

**Issue by modusc896d352** [RazTools/Studio#58]
imagine if you're trying to sort dozens and dozens of baked-in C# code through dozens and dozens of unity asset files. that may include files like "level0", "globalgamemanagers" and/or even a single file that ends with the "bundle" file extension.

AssetMap building is great but it can only gather tons of animations, models, materials, sounds, textures and videos. but not MonoBehaviour entries. despite them being basically the "proteins" of an entire Unity game. despite tons of them existing in all of these asset files.

trying to preview an MonoBehaviour entry has you lose minds over which "FileID" (if that) and PathID this entry is referencing, so if possible (big if) i need to see AssetMap build include MonoBehaviour entries as well, thanks in advance.

**Comment by Modder4869** [comment]
try disabling minimal assetmap if that doesnt include it then just edit the code

**Comment by modusc896d352** [comment]
OK, i don't really know how to disable minimal assetmap so i'll see what i can do

the problem i'm having here is the game has like dozens of MonoBehaviour entries spread across various packed files, and though i could just edit the code sure, i don't know which code i would really need to edit here given that, again, there are so many of them to choose from.

actually i don't even want to *edit the code*, i just want to *see* it instead. but i just want to see them sorted out into a somewhat-comprehensive list somewhat.

**Comment by Modder4869** [comment]
by editing i meant studio code https://github.com/RazTools/Studio/blob/5e354694351846981010f169f1b117f96c589877/AssetStudio/AssetsHelper.cs#L367
also can just use cli and dummypath option to extract all monobehavior

**Comment by modusc896d352** [comment]
i guess there's that...
