### ISSUE TITLE
[Request] Support for 穿越火线-枪战王者 (Crossfire Mobile China)

### ISSUE THREAD

**Issue by Mika1412x** [RazTools/Studio#60]
### Hello

Currently, I am experiencing some issues related to the game [穿越火线-枪战王者](https://cfm.qq.com/).
Specifically, it cannot be loaded in the Studio.

![Untitled](https://github.com/RazTools/Studio/assets/147727121/f3f54228-0abc-4b0e-af8a-2037ee3a99bc)

I hope you can provide support for this game in the future.

#### Additional Information:
- Studio Version: **v1.00.00+51a14820a80707c75265a85791210e914151c49b** (latest).
- Game Version:  **1.0.370.670** (latest).
- Operating System: **Android/iOS**.

**Comment by qingchunnh** [comment]
我猜这个游戏应该有加密或者混淆之类的东西，这个软件最早的用途是给某二次元游戏使用的，感觉不太可能专门为了这游戏修改此软件

**Comment by Razmoth** [comment]
Greetings,

The game encrypt `SerializedFile` header with xored constant `0x36392029` on all 4 fields except version, should be `11` instead of `12`.
