### ISSUE TITLE
PGR CN Texture2D error

### ISSUE THREAD

**Issue by 809781347** [RazTools/Studio#63]
Some Textures will have this error and will not display the full texture
![image](https://github.com/RazTools/Studio/assets/100351684/965c64a8-d007-42e4-b1b4-e63c4687982f)
![image](https://github.com/RazTools/Studio/assets/100351684/468408fa-95e7-4dbf-8611-d9e344e51ead)
Is this a problem with the game itself or with the tools ？

**Comment by Modder4869** [comment]
send sample

**Comment by 809781347** [comment]
What samples do I need to send?
I have the texture of a character from Two different tools
This is extracted from tools
The texture exported from the tool is like a large image cut into several small texture images arranged randomly
[Texture2D.zip](https://github.com/RazTools/Studio/files/14129361/Texture2D.zip)

This is extracted from game by ninja ripper 
It‘s extracted by the ninja ripper is the normal texture picture
[Ninja.zip](https://github.com/RazTools/Studio/files/14129365/Ninja.zip)

**Comment by Modder4869** [comment]
original bundle file that include it

**Comment by 809781347** [comment]
Is this it?
[1.zip](https://github.com/RazTools/Studio/files/14135737/1.zip)

**Comment by Modder4869** [comment]
loads and shows fine for me , use latest studio version from github actions

**Comment by 809781347** [comment]
Thanks for the answer, it seems that this problem occurs when I read all the files in this character folder, and no texture error occurs when I read only this file

**Comment by Modder4869** [comment]
studio version?

**Comment by 809781347** [comment]
The new action version

**Comment by 809781347** [comment]
Some textures also have errors when reading multiple files, but when I read only one of the files, the texture does not have errors

**Comment by Modder4869** [comment]
not much i can do unless you can limit it to few files that can reproduce the issue

**Comment by 809781347** [comment]
thanks，I will try later to see if I can reproduce the problem with limited files

**Comment by Razmoth** [comment]
Greetings,

3592566 should fix this issue.

**Comment by 809781347** [comment]
Thanks, this version does fix the texture error
