### ISSUE TITLE
Can not export

### ISSUE THREAD

**Issue by 3286210474** [RazTools/Studio#64]
I installed the Microsoft.NET SDK 6.0.418 and Microsoft.NET SDK 7.0.405 and Microsoft.NET SDK 8.0.101.They are all up to date.But I can not use normally from v0.90.40 to v1.36.0. I can not use "Model--export all objects(split)" in v0.90.40 and v1.00.00. I can not use normally "Model" and "Export" to export anything in v1.36.0. I'm still using v0.90.10.

**Comment by Modder4869** [comment]
please follow the bug report template , this tells us nothing
