### ISSUE TITLE
can not use "Model--export all objects(split)" to export

### ISSUE THREAD

**Issue by 3286210474** [RazTools/Studio#65]
**Describe the bug**
Can not use "Model--export all objects(split)" to export models.

**To Reproduce**
1. Go to "Model"
2. Click on "export all objects(split)"
3. See error

**Screenshots**
![屏幕截图 2024-02-03 210122](https://github.com/RazTools/Studio/assets/88732725/db6e45a1-eb5c-406a-860f-cbea3dcd8b08)
![屏幕截图 2024-02-03 210310](https://github.com/RazTools/Studio/assets/88732725/0a724d37-fabe-48fa-bbc6-902ea7873ff7)

**Version**
v0.90.40 and v1.00.00

**Unity Version**
2018.4.31f12

**Game/Sample**
ShiningNikki

**Comment by Modder4869** [comment]
still tells us nothing and use latest version 1.36 and you didnt send game file sample , dont open another issue just send here
