### ISSUE TITLE
Can not export .fbx models

### ISSUE THREAD

**Issue by 3286210474** [RazTools/Studio#66]
**Describe the bug**
Can not export .fbx models.

**To Reproduce**
1. Go to 'Model'
2. Click on 'export all objects (split)'
3. See error
and
1. Go to 'Export'
2. Click on 'All assets'
3. See error

**Screenshots**
![屏幕截图 2024-02-03 214501](https://github.com/RazTools/Studio/assets/88732725/e7f709a3-f451-4914-98c9-ae6d56ed8477)

**Version**
v1.36.00

**Unity Version**
2020.3.33f1c2

**Game/Sample**
[art_models_actor_prelogin_assets_xiaoyanb_eb059c0660ca88a7202912ba9ce31db4.zip](https://github.com/RazTools/Studio/files/14151619/art_models_actor_prelogin_assets_xiaoyanb_eb059c0660ca88a7202912ba9ce31db4.zip)

**Comment by Modder4869** [comment]
thats still not latest actions download [this](https://github.com/RazTools/Studio/actions/runs/7767294326)

**Comment by Modder4869** [comment]
stop closing the issue and creating new ones
