### ISSUE TITLE
The program wont launch, not even the basic original versions

### ISSUE THREAD

**Issue by maroscantcode** [RazTools/Studio#67]
![Screenshot 2024-02-03 222454](https://github.com/RazTools/Studio/assets/158780125/62067ff7-5751-4e12-9ff5-1bc2c116f051)
It just wont open any versions i tried, all i can get is this, which flashes on my screen for like a second and then closes.

**Comment by Modder4869** [comment]
are you extracting it?

**Comment by maroscantcode** [comment]
i am, and just now i realized when i dont extract it, it works, thanks for the reply anyways, feel free to close this thank you

**Comment by Modder4869** [comment]
thats weird something on your pc might be blocking it , using it inside archive is not recommended
