### ISSUE TITLE
Loading a large number of files causes OOM

### ISSUE THREAD

**Issue by Sakura-Luna** [RazTools/Studio#73]
This is an obvious problem. The program lacks memory control. The GUI loading large amounts of data will actively exhaust memory and cause system crashes. Preventive measures should be added.

**Version** `v1.00.00`.

**Comment by Modder4869** [comment]
please read the guide in readme and 1.0.0 is beyond outdated download latest action , with this fork of studio you rarely need to load so many files at once

**Comment by Sakura-Luna** [comment]
> please read the guide in readme and 1.0.0 is beyond outdated download latest action , with this fork of studio you rarely need to load so many files at once

Some games use a large number of random file names to store resources, which makes it difficult to obtain the target content and opening a large number of files is unavoidable. Moreover, it is difficult for users to know whether loading a file will exceed the upper limit of memory resources, so it is an unsafe design to have no memory control.

**Comment by Modder4869** [comment]
thats why you can build assetmap and cabmap and load assets by name then when you load just one file that has the asset you want all other dependencies would load too and you can always use cli to export 
and if you dont have enough ram you can always set page file

**Comment by Razmoth** [comment]
Greetings,

Due to how `AssetStudio` is structured/designed, this is normal behaviour and is to be expected when loading large number of files.

**Comment by Sakura-Luna** [comment]
> Due to how `AssetStudio` is structured/designed, this is normal behaviour and is to be expected when loading large number of files.

If the crash caused by the OOM of the program itself is not serious, but the program eventually causes the Windows system to crash, this is extremely unsafe behavior. Considering the performance of popular devices and the size of the games, preventive measures are necessary.
Controlling the amount of memory used by a program is best practice, and the most basic is to warn when trying to load a large file or a large number of files, for example (16 Gb).

**Comment by Modder4869** [comment]
what even is your ram? system crash would happen if your pc has page file disabled and it is not tool fault if crash is caused by user actions and like i said before most stuff can be extracted without having to load whole game this the most important point of this fork

**Comment by Sakura-Luna** [comment]
> what even is your ram? system crash would happen if your pc has page file disabled and it is not tool fault if crash is caused by user actions and like i said before most stuff can be extracted without having to load whole game this the most important point of this fork

I did not disable the memory page, but in fact its capabilities are limited. If the page uses up all the C drive space, the system will crash directly. In fact, many software will also place the running cache path on the C drive, which further takes up space.

**Comment by Modder4869** [comment]
you can set which disk your page file is stored at

**Comment by Sakura-Luna** [comment]
I understand that the CLI can unpack files to disk, but this has nothing to do with loading the GUI. The program never warns the user that "if you load a file that is too large, it will directly eat up your ram", which is rare, especially It's 2024 now.

**Comment by Sakura-Luna** [comment]
> you can set which disk your page file is stored at

Some versions of Windows have a bug where they don't use space from other disks.

**Comment by Modder4869** [comment]
well dont have suggestions anymore just dont load whole game i guess

**Comment by Sakura-Luna** [comment]
> well dont have suggestions anymore just dont load whole game i guess

Yes, if a patch is not intended, warning users is necessary to load game data with caution.

**Comment by Modder4869** [comment]
i dont think you can realistically calculate that , and thats why the guide in readme shows the correct way to use the tool

**Comment by Sakura-Luna** [comment]
> i dont think you can realistically calculate that , and thats why the guide in readme shows the correct way to use the tool

Yes, it is impossible to calculate the size before decompression, so the best practice is memory management. Once the program exceeds the rated memory usage, it will be terminated immediately. This is very common, especially in high-level languages ​​such as Java or C#.
