### ISSUE TITLE
Exporting grouped ByContainer is broken in both GUI and CLI

### ISSUE THREAD

**Issue by wangyi041228** [RazTools/Studio#75]
GUI: exported files list in the main folder.
CLI: just work like ByType.
`AssetStudio.CLI "C:\Program Files (x86)\Hearthstone\Data\Win\cardtexture_base_global-fc6d50fb-texture-6.unity3d" "D:\Desktop\0\240213\TEST" --game GI --types Texture2D AudioClip --group_assets ByContainer`

**Version**
`net8.0-f2d65e458c8139069a379d0836f2efe660831d06`.
https://github.com/RazTools/Studio/releases/tag/v1.36.00

**Unity Version**
For example `2021.3.25f1`.

**Game/Sample**
`Hearthstone`

**Comment by Modder4869** [comment]
Use latest actions not release

**Comment by wangyi041228** [comment]
Tried https://github.com/RazTools/Studio/actions/runs/7862989983
[net8.0-e1d7f5301aa015a3386e245312205969f763c9ae](https://github.com/RazTools/Studio/actions/runs/7862989983/artifacts/1236645379)
But, it doesn't work as well. And I raised another issue about exporting multi files shared a name.
https://github.com/RazTools/Studio/issues/76

**Comment by Modder4869** [comment]
wym doesnt work ? and dont open multiple issues before checking options it is called allow duplicate , in gui it is options>allow duplicate in cli it is in AssetStudio.CLI.dll.config

**Comment by Modder4869** [comment]
why even using GI as game ? it is Normal game 
`AssetStudio.CLI.exe .\carddef_base_global-b10736ab-prefab-2.unity3d . --game Normal --group_assets ByContainer`
worked fine for me i dont know whats you issue

**Comment by wangyi041228** [comment]
Thanks for you guide. CLI worked well for me now.
But the GUI doesn't. Would you please test it?

**Comment by wangyi041228** [comment]
After more tests:
net8.0-e1d7f5301aa015a3386e245312205969f763c9ae worked for MonoBehaviour and AudioClip, but failed to export any Texture2D files.
net8.0-f2d65e458c8139069a379d0836f2efe660831d06 worked for All but failed to group ByContainer.


[cardtexture_base_global-fc6d50fb-texture-6.unity3d.txt](https://github.com/RazTools/Studio/files/14284972/cardtexture_base_global-fc6d50fb-texture-6.unity3d.txt)

**Comment by Modder4869** [comment]
ye thats bug kinda but like your container name look like `2c3f038a3da34869ab2db94526cf4683` because it is hashed but studio expecting something like path `2c3f038a3da34869ab2db94526cf4683/` so it fails to
