### ISSUE TITLE
v1.36.00 does not work on my computer

### ISSUE THREAD

**Issue by DDXDB** [RazTools/Studio#77]
Run GUI or CLI, nothing happens.
Programs flash by in Task Manager.
Whether it's Releases or Actions
Already attempted
net8.0-2e268e6283cf3339bdab90d11d0e9b3a9b41fc89
net7.0-e1d7f5301aa015a3386e245312205969f763c9ae
net8.0-e1d7f5301aa015a3386e245312205969f763c9ae

**Comment by DDXDB** [comment]
Correction, this version works
net8.0-e19d7b91feb78072b96f1fe26eb1edccc1245fef

**Comment by DDXDB** [comment]
@Razmoth 
Can't close the issue, I think.
Net8.0 - e19d7b91feb78072b96f1fe26eb1edccc1245fef any later version could not be started on my computer...

**Comment by redsigma** [comment]
Why not use the version from the Release ?

**Comment by DDXDB** [comment]
> Why not use the version from the Release ?

e1d7f5301aa015a3386e245312205969f763c9ae is Release

**Comment by redsigma** [comment]
> > Why not use the version from the Release ?
> 
> [e1d7f53](https://github.com/RazTools/Studio/commit/e1d7f5301aa015a3386e245312205969f763c9ae) is Release

If the app doesnt launch then I suggest to wipe .NET and install it again.

**Comment by DDXDB** [comment]
> > > Why not use the version from the Release ?
> > 
> > 
> > [e1d7f53](https://github.com/RazTools/Studio/commit/e1d7f5301aa015a3386e245312205969f763c9ae) is Release
> 
> If the app doesnt launch then I suggest to wipe .NET and install it again.

It works for me! I uninstalled all .NET and then install Visual Studio, e1d7f5301aa015a3386e245312205969f763c9ae now work for me
