### ISSUE TITLE
Bug: v0.90 AssetStudioCLI cannot write to file with  Parallel call.

### ISSUE THREAD

**Issue by peaceshi** [RazTools/Studio#8]
v0.18.60 works fine.
v0.80.65 works fine.
https://github.com/kongying-tavern/it-is-a-exporter/blob/main/scripts/Resources.csx#L37-L44

**Comment by peaceshi** [comment]
use process monitor or other tools to find `Write file` operation.
![image](https://github.com/RazTools/Studio/assets/10380828/f5182af0-4813-4d4b-bb9e-411efb8ead77)

**Comment by Razmoth** [comment]
Greetings,

Should be fixed.

**Comment by peaceshi** [comment]
Yes, thank you!
